-- User-submitted Build Guides ("User made builds" page - see
-- src/pages/CreateBuildPage.jsx / src/pages/UserBuildsPage.jsx).
--
-- Unlike every other table so far (short_links, issue_reports, page_events -
-- all insert-only from `anon`, read exclusively via direct psql or a
-- single-row SECURITY DEFINER lookup, see 001_init.sql's own comments on
-- why), this table is deliberately BROWSABLE: the entire point of "User made
-- builds" is a public listing anyone can page through, so `anon` gets a real
-- SELECT grant here, not just INSERT.
--
-- That SELECT is restricted by RLS to `hidden = false` - the escape hatch for
-- a build that turns out to be spam/abusive. There is no moderation UI or
-- endpoint that can flip it: consistent with issue_reports' own "triage is
-- done via a direct Postgres client" precedent, hiding a build is a manual
-- `update public.user_builds set hidden = true where id = ...` run by
-- whoever has real DB access. Nothing here grants `anon` UPDATE, so this
-- can't be done through PostgREST no matter what a crafted request tries.
-- `edit_token_hash`: sha256 (hex) of a random 24-byte token generated by the
-- Node route on creation (see server/src/routes/userBuilds.js) and shown to
-- the submitter exactly once - never stored raw, same principle as a
-- password hash. The submitter's browser keeps the raw token in localStorage
-- (see src/utils/myBuilds.js) as its only proof of authorship; there are no
-- accounts, so this token IS the credential. Never selectable (see the
-- column-scoped grant below) - it doesn't need to be, since editing goes
-- through the update_user_build() RPC, not a plain row read.
create table public.user_builds (
  id               bigint generated always as identity primary key,
  name             text not null,
  tagline          text not null default '',
  styles           text[] not null default '{}',
  author_name      text not null default '',
  payload          jsonb not null,
  edit_token_hash  text not null,
  hidden           boolean not null default false,
  created_at       timestamptz not null default now()
);

create index user_builds_created_at_idx on public.user_builds (created_at desc) where not hidden;

alter table public.user_builds enable row level security;

grant insert on public.user_builds to anon;
-- Column-scoped, not a blanket `grant select on public.user_builds` - Postgres
-- enforces this per-column regardless of what any future query asks for, so
-- `edit_token_hash` can never leak through this table even if a route forgets
-- to restrict its own `select=` list.
grant select (id, name, tagline, styles, author_name, payload, hidden, created_at) on public.user_builds to anon;

create policy user_builds_insert on public.user_builds
  for insert to anon with check (true);

-- The listing page never needs `payload` (the full build) - only the single
-- open card does (see GET /api/user-builds/:id, a Node route, not a direct
-- PostgREST call - kept behind the Node service rather than exposed straight
-- through PostgREST so request validation/shaping stays server-side, same as
-- every other write path in this app). `payload` is technically fetchable
-- straight through PostgREST by anyone who requests it - it was never
-- sensitive (it's exactly what its own author intended to publish) so that's
-- an acceptable simplification rather than adding a second view.
create policy user_builds_select on public.user_builds
  for select to anon using (not hidden);

-- ─────────────────────────────────────────────────────────────────────────
-- Editing without accounts: the ONLY way to update a row. `anon` has no
-- UPDATE grant on the table at all (a blanket `for update using (true)`
-- policy would let anyone rewrite anyone else's build with no token check
-- whatsoever, since PostgREST is reachable directly, not just through the
-- Node service - see src/utils/api.js's comments on that). This function is
-- SECURITY DEFINER (same trick as get_short_link_payload below), so its own
-- UPDATE runs as the migration owner regardless of anon's table grants - the
-- WHERE clause itself is what gates it: a row only updates if the hash the
-- caller supplies matches the one stored at creation. Anyone can call this
-- RPC (it's granted to anon), but doing so successfully requires already
-- knowing the exact 24-byte token - not something a request can guess or
-- enumerate its way into.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.update_user_build(
  p_id bigint,
  p_token_hash text,
  p_name text,
  p_tagline text,
  p_styles text[],
  p_payload jsonb
)
returns table (id bigint)
language sql
security definer
set search_path = public
as $$
  update public.user_builds
  set name = p_name, tagline = p_tagline, styles = p_styles, payload = p_payload
  where user_builds.id = p_id and user_builds.edit_token_hash = p_token_hash
  returning user_builds.id;
$$;

revoke all on function public.update_user_build(bigint, text, text, text, text[], jsonb) from public;
grant execute on function public.update_user_build(bigint, text, text, text, text[], jsonb) to anon;
